package com.qf.cxf1.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-31T09:55:25.729+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "WeatherServiceService", 
                  wsdlLocation = "http://127.0.0.1:98/weather?wsdl",
                  targetNamespace = "http://service.cxf1.qf.com/") 
public class WeatherServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf1.qf.com/", "WeatherServiceService");
    public final static QName WeatherServicePort = new QName("http://service.cxf1.qf.com/", "WeatherServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:98/weather?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WeatherServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:98/weather?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WeatherServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WeatherServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WeatherServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WeatherServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WeatherServicePort")
    public WeatherService getWeatherServicePort() {
        return super.getPort(WeatherServicePort, WeatherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WeatherServicePort")
    public WeatherService getWeatherServicePort(WebServiceFeature... features) {
        return super.getPort(WeatherServicePort, WeatherService.class, features);
    }

}
